/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ProductoControlador;
import controlador.VentaControlador;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 * width
 *
 * @author user
 */
public class frmActualizarEliminarProducto extends javax.swing.JFrame {

    /**
     * Creates new form frmActualizarEliminarProducto
     */
    public frmActualizarEliminarProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Editar Registros");
        cbxCampo.removeAllItems();
        cbxCampo.addItem("nombreProducto");
        cbxCampo.addItem("precio");
        cbxCampo.addItem("cantidad");
        this.setSize(560, 640);

    }
    private int idProductoActual = -1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNuevoValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxCampo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnMostrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnVolver1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Digite nuevo valor:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtNuevoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoValorActionPerformed(evt);
            }
        });
        getContentPane().add(txtNuevoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 350, 40));

        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        getContentPane().add(cbxCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 300, 50));

        jLabel3.setText("Editar Seleccion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 100, 40));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 520, 260));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 90, 40));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 90, 40));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 90, 40));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 40, 40));

        btnVolver1.setText("Vover");
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNuevoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoValorActionPerformed

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        if (idProductoActual == -1) {
            JOptionPane.showMessageDialog(this, "Primero busca un producto válido.");
            return;
        }

        if (cbxCampo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un campo para actualizar.");
            return;
        }

        try {
            String campo = cbxCampo.getSelectedItem().toString();
            String valor = txtNuevoValor.getText();

            ProductoControlador pc = new ProductoControlador();
            if (pc.actualizarCampoProducto(idProductoActual, campo, valor)) {
                JOptionPane.showMessageDialog(this, "Producto actualizado.");
                cargarTablaProductos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (idProductoActual == -1) {
            JOptionPane.showMessageDialog(this, "Primero busca un producto válido.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de eliminar este producto?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            ProductoControlador pc = new ProductoControlador();
            if (pc.eliminarProducto(idProductoActual)) {
                JOptionPane.showMessageDialog(this, "Producto eliminado.");
                cargarTablaProductos();
                // Limpiar campos después de eliminar
                txtIdProducto.setText("");
                txtNuevoValor.setText("");
                idProductoActual = -1;
                btnActualizar.setEnabled(false);
                btnEliminar.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar.");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        VentaControlador vc = new VentaControlador();
        cargarTablaProductos();
        vc.cargarTablaStockDisponible(tblProductos);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String codigo = txtIdProducto.getText().trim();

        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa el código del producto (por ejemplo: PR0005).");
            return;
        }

        ProductoControlador pc = new ProductoControlador();
        Producto p = pc.obtenerProductoPorCodigo(codigo);

        if (p != null) {
            idProductoActual = p.getId(); // Guardamos el ID numérico
            txtNuevoValor.setText(p.getNombre());
            btnActualizar.setEnabled(true);
            btnEliminar.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Producto no encontrado.");
            idProductoActual = -1;
            btnActualizar.setEnabled(false);
            btnEliminar.setEnabled(false);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        // TODO add your handling code here:
        frmPrincipal principal = new frmPrincipal();
        principal.setLocationRelativeTo(null);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void cargarTablaProductos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Código", "Nombre", "Precio", "Cantidad"});

        VentaControlador vc = new VentaControlador();
        List<String[]> productos = vc.obtenerProductosConStock();

        for (String[] fila : productos) {
            modelo.addRow(fila);
        }

        tblProductos.setModel(modelo);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JComboBox<String> cbxCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNuevoValor;
    // End of variables declaration//GEN-END:variables
}
