package vista;

import controlador.VentaControlador;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class frmPrediccionVentas extends javax.swing.JFrame {

    /**
     * Creates new form frmPrediccionVentas
     */
    public frmPrediccionVentas() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Prediccion de Ventas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxDias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrediccion = new javax.swing.JTable();
        btnMostrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "14", "30" }));
        cbxDias.setBorder(javax.swing.BorderFactory.createTitledBorder("Elegir dias:"));
        getContentPane().add(cbxDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 50));

        tblPrediccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrediccion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 510, 300));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 40));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver-al-pasado.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        int dias = Integer.parseInt(cbxDias.getSelectedItem().toString());
        VentaControlador vc = new VentaControlador();
        List<String[]> prediccion = vc.obtenerProductosMasVendidos(dias);

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Código", "Nombre", "Cantidad Vendida"});
        for (String[] fila : prediccion) {
            modelo.addRow(fila);
        }
        tblPrediccion.setModel(modelo);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        frmPrincipal principal = new frmPrincipal();
        principal.setLocationRelativeTo(null);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxDias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrediccion;
    // End of variables declaration//GEN-END:variables
}
