/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.UsuarioControlador;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author user
 */
public class frmRegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistroUsuario
     */
    public frmRegistroUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Registro Usuario");
        this.setSize(400, 470);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        cbxRol = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrarUsuario = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 210, 40));

        jLabel2.setText("Correo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 210, 40));

        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        getContentPane().add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 130, 40));

        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dueño", "asistente", "empleado" }));
        getContentPane().add(cbxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 160, 40));

        jLabel4.setText("Rol:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        btnRegistrarUsuario.setText("Registrar");
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 110, 40));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
        Usuario u = new Usuario();
        u.setNombre(txtNombre.getText());
        u.setCorreo(txtCorreo.getText());
        u.setContrasena(new String(txtContrasena.getPassword()));
        u.setRol(cbxRol.getSelectedItem().toString());

        UsuarioControlador uc = new UsuarioControlador();

        if (uc.registrarUsuario(u)) {
            JOptionPane.showMessageDialog(this, "Usuario registrado correctamente");
            limpiarCamposUsuario();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar usuario");
        }
        if (!validarCamposUsuario()) {
            return;
        }

    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        frmPrincipal principal = new frmPrincipal();
        principal.setLocationRelativeTo(null);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    private boolean validarCamposUsuario() {
        if (txtNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa el nombre");
            txtNombre.requestFocus();
            return false;
        }
        if (txtCorreo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa el correo");
            txtCorreo.requestFocus();
            return false;
        }
        if (txtContrasena.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Ingresa la contraseña");
            txtContrasena.requestFocus();
            return false;
        }
        return true;
    }

    private void limpiarCamposUsuario() {
        txtNombre.setText("");
        txtCorreo.setText("");
        txtContrasena.setText("");
        cbxRol.setSelectedIndex(0); // O ajusta el valor por defecto
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
