/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.VentaControlador;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Venta;

/**
 *
 * @author user
 */
public class frmVenta extends javax.swing.JFrame {

    /**
     * Creates new form frmVenta
     */
    // Atributo global en la clase
    VentaControlador vc = new VentaControlador();

    public frmVenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Registro Venta");

        List<String> codigos = vc.obtenerCodigosConNombre();
        for (String c : codigos) {
            cbxCodigoProducto.addItem(c);
        }

        cbxTipo.removeAllItems();
        cbxTipo.addItem("Boleta");
        cbxTipo.addItem("Factura");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxCodigoProducto = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnAnadir = new javax.swing.JButton();
        cbxTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxCodigoProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto:"));
        getContentPane().add(cbxCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 250, 60));

        txtCantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad:"));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 50));

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas.png"))); // NOI18N
        btnRegistrar.setText("Registrar Venta");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 170, 40));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver-al-pasado.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 100, 40));

        btnAnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir-al-carrito.png"))); // NOI18N
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 50, 40));

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Venta"));
        getContentPane().add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 240, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String tipo = cbxTipo.getSelectedItem().toString();
        vc.registrarVentaCarrito(tipo);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        frmPrincipal principal = new frmPrincipal();
        principal.setLocationRelativeTo(null);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        // TODO add your handling code here:
        String seleccionado = cbxCodigoProducto.getSelectedItem().toString();
        String codigo = seleccionado.split(" - ")[0];
        int cantidad = Integer.parseInt(txtCantidad.getText());
        vc.agregarAlCarrito(codigo, cantidad);
        vc.actualizarComboBox(cbxCodigoProducto);

    }//GEN-LAST:event_btnAnadirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxCodigoProducto;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
